#ifndef FILETEXTREPLACE_GLOBAL_H
#define FILETEXTREPLACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILETEXTREPLACE_LIBRARY)
#  define FILETEXTREPLACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILETEXTREPLACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILETEXTREPLACE_GLOBAL_H
