#ifndef REMOVEDIRECTORY_GLOBAL_H
#define REMOVEDIRECTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REMOVEDIRECTORY_LIBRARY)
#  define REMOVEDIRECTORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define REMOVEDIRECTORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REMOVEDIRECTORY_GLOBAL_H
