#ifndef PROCESSXMLLISTGENERATOR_GLOBAL_H
#define PROCESSXMLLISTGENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROCESSXMLLISTGENERATOR_LIBRARY)
#  define PROCESSXMLLISTGENERATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROCESSXMLLISTGENERATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROCESSXMLLISTGENERATOR_GLOBAL_H
