#ifndef CONVERTCHECKER_GLOBAL_H
#define CONVERTCHECKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONVERTCHECKER_LIBRARY)
#  define CONVERTCHECKERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONVERTCHECKERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONVERTCHECKER_GLOBAL_H
