#ifndef BUFFEREDCOPY_GLOBAL_H
#define BUFFEREDCOPY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BUFFEREDCOPY_LIBRARY)
#  define BUFFEREDCOPYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BUFFEREDCOPYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BUFFEREDCOPY_GLOBAL_H
