#ifndef FILESEARCHDIALOG_GLOBAL_H
#define FILESEARCHDIALOG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILESEARCHDIALOG_LIBRARY)
#  define FILESEARCHDIALOGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILESEARCHDIALOGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILESEARCHDIALOG_GLOBAL_H
