#ifndef PROCESSXMLBUILDER_GLOBAL_H
#define PROCESSXMLBUILDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROCESSXMLBUILDER_LIBRARY)
#  define PROCESSXMLBUILDERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROCESSXMLBUILDERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROCESSXMLBUILDER_GLOBAL_H
