#ifndef SEARCHXMLBUILDER_GLOBAL_H
#define SEARCHXMLBUILDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SEARCHXMLBUILDER_LIBRARY)
#  define SEARCHXMLBUILDERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SEARCHXMLBUILDERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SEARCHXMLBUILDER_GLOBAL_H
