#ifndef FFPROBEEXTPID_GLOBAL_H
#define FFPROBEEXTPID_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FFPROBEEXTPID_LIBRARY)
#  define FFPROBEEXTPIDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FFPROBEEXTPIDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FFPROBEEXTPID_GLOBAL_H
