#ifndef FILEINFODIALOG_GLOBAL_H
#define FILEINFODIALOG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FILEINFODIALOG_LIBRARY)
#  define FILEINFODIALOGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FILEINFODIALOGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FILEINFODIALOG_GLOBAL_H
