#ifndef TAKELINEPLUGIN_GLOBAL_H
#define TAKELINEPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TAKELINEPLUGIN_LIBRARY)
#  define TAKELINEPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TAKELINEPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TAKELINEPLUGIN_GLOBAL_H
