#ifndef MAKEDIRECTORY_GLOBAL_H
#define MAKEDIRECTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MAKEDIRECTORY_LIBRARY)
#  define MAKEDIRECTORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MAKEDIRECTORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MAKEDIRECTORY_GLOBAL_H
