#!/bin/bash
ROOTDIR=$(cd $(dirname $0); pwd)
export LD_LIBRARY_PATH=${ROOTDIR}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export QT_PLUGIN_PATH=${ROOTDIR}${QT_PLUGIN_PATH:+:$QT_PLUGIN_PATH}

QT_QPA_PLATFORM=xcb "$1"
