#ifndef PROFILEXMLBUILDER_GLOBAL_H
#define PROFILEXMLBUILDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROFILEXMLBUILDER_LIBRARY)
#  define PROFILEXMLBUILDERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROFILEXMLBUILDERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROFILEXMLBUILDER_GLOBAL_H
