#ifndef XMLRESOLVER_GLOBAL_H
#define XMLRESOLVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XMLRESOLVER_LIBRARY)
#  define XMLRESOLVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XMLRESOLVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XMLRESOLVER_GLOBAL_H
