#ifndef PLUGINSTREE_GLOBAL_H
#define PLUGINSTREE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGINSTREE_LIBRARY)
#  define PLUGINSTREESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGINSTREESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGINSTREE_GLOBAL_H
