#ifndef CONSOLEBASE_GLOBAL_H
#define CONSOLEBASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONSOLEBASE_LIBRARY)
#  define CONSOLEBASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONSOLEBASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONSOLEBASE_GLOBAL_H
