#ifndef STRINGTABLE_GLOBAL_H
#define STRINGTABLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STRINGTABLE_LIBRARY)
#  define STRINGTABLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define STRINGTABLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STRINGTABLE_GLOBAL_H
