#ifndef REGEXPINPUTRENAME_GLOBAL_H
#define REGEXPINPUTRENAME_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REGEXPINPUTRENAME_LIBRARY)
#  define REGEXPINPUTRENAMESHARED_EXPORT Q_DECL_EXPORT
#else
#  define REGEXPINPUTRENAMESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // REGEXPINPUTRENAME_GLOBAL_H
