#ifndef EXTRAFUNCTIONSTABLE_GLOBAL_H
#define EXTRAFUNCTIONSTABLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EXTRAFUNCTIONSTABLE_LIBRARY)
#  define EXTRAFUNCTIONSTABLESHARED_EXPORT Q_DECL_EXPORT
#else
#  define EXTRAFUNCTIONSTABLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EXTRAFUNCTIONSTABLE_GLOBAL_H
